<?php

namespace Database\Seeders;

use App\Models\DetailAudit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AuditTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $audit = [
            [
                'id_audit' => '1',
                'tools' => 'Obeng Plus Besar',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Kunci Pas Ring Set',
                'qty' => '1',
                'desc' => '8,9,11,13,19,22,24,27,30,32',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Thermo Gun',
                'qty' => '1',
                'desc' => 'Tekiro',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Slepan Kecil',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Palu Kecil',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Palu Besar',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Kunci L Bintang',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Tracker Beraing Kaki 3',
                'qty' => '1',
                'desc' => 'Size 16 Inch',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Hydraulic Pump',
                'qty' => '1',
                'desc' => 'Pompa Tangan',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Hydraulic Cylinder',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '1',
                'tools' => 'Snapring',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Kunci Shock',
                'qty' => '1',
                'desc' => 'Shock L dan Putar',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Kunci Inggris',
                'qty' => '1',
                'desc' => '6" dan 12"',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Kunci Oil Filter',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Obeng Plus',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Tang Ampere',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Vibrasi Meter',
                'qty' => '1',
                'desc' => 'Benetech',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Kunci Pas Ring Set',
                'qty' => '1',
                'desc' => '8,9,11,13,18,22,24,27,30,32',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Thermo Gun',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Obeng Ketok',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Palu',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Skun Kabel',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Kikir',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Gun Grease',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Sambungan Shock',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Kunci Shock Set',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Kunci L mm',
                'qty' => '1',
                'desc' => '2,2.5,3,4,5,6,8,10',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '2',
                'tools' => 'Kunci L Bintang',
                'qty' => '3',
                'desc' => '6,8',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Obeng Plus',
                'qty' => '1',
                'desc' => 'Besar, Sedang, dan Kecil',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Obeng Minus',
                'qty' => '1',
                'desc' => 'Besar, Sedang, dan Kecil',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Kunci Oil Filter',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Kunci Pas Ring Set',
                'qty' => '1',
                'desc' => '8(2),9,11,13,14,19(2),22,24,27,30,32',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Thermo Gun',
                'qty' => '1',
                'desc' => 'Tekiro',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Tang Kombinasi',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Tang Potong',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Kunci Inggris',
                'qty' => '1',
                'desc' => '10" dan 12"',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Kunci Pipa',
                'qty' => '1',
                'desc' => '14"',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Kunci L mm',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Kunci L Bintang',
                'qty' => '1',
                'desc' => '8,5,4,3,1',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Oring Box',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Tang Ampere',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Vibrasi Meter',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Kunci Shock L',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Thermo Gun',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
            [
                'id_audit' => '3',
                'tools' => 'Sanpring',
                'qty' => '1',
                'desc' => '-',
                'assesment' => 'Ada',
                'note' => '-',
            ],
        ];
        DetailAudit::insert($audit);
    }
}
