<?php

namespace Database\Seeders;

use App\Models\PipingMaterial;
use App\Models\PipingMaterialVendorPrice;
use App\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PipingMaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = Supplier::take(5)->pluck('id')->toArray();
        $defaultSupId = !empty($suppliers) ? $suppliers[0] : null;

        $items = [
            // =========================================================================
            // 1. KATEGORI: PIPE (Pipa) - 12 Items
            // =========================================================================
            [
                'item_code'             => 'PIP-ALU-020',
                'category'              => 'pipe',
                'material_type'         => 'Aluminium Airnet / AIRpipe',
                'item_name'             => 'Pipa Aluminium Compressed Air 20mm (1/2") x 6m',
                'size'                  => '20mm (1/2")',
                'connection_type'       => 'Quick-Fit / Socket',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Standar instalasi udara bertekanan max 15 bar, powder coated blue',
                'price_idr'             => 285000,
            ],
            [
                'item_code'             => 'PIP-ALU-025',
                'category'              => 'pipe',
                'material_type'         => 'Aluminium Airnet / AIRpipe',
                'item_name'             => 'Pipa Aluminium Compressed Air 25mm (3/4") x 6m',
                'size'                  => '25mm (3/4")',
                'connection_type'       => 'Quick-Fit / Socket',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Standar instalasi udara bertekanan max 15 bar, powder coated blue',
                'price_idr'             => 395000,
            ],
            [
                'item_code'             => 'PIP-ALU-040',
                'category'              => 'pipe',
                'material_type'         => 'Aluminium Airnet / AIRpipe',
                'item_name'             => 'Pipa Aluminium Compressed Air 40mm (1-1/2") x 6m',
                'size'                  => '40mm (1-1/2")',
                'connection_type'       => 'Quick-Fit / Socket',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Standar header / sub-header udara bertekanan max 15 bar',
                'price_idr'             => 680000,
            ],
            [
                'item_code'             => 'PIP-ALU-050',
                'category'              => 'pipe',
                'material_type'         => 'Aluminium Airnet / AIRpipe',
                'item_name'             => 'Pipa Aluminium Compressed Air 50mm (2") x 6m',
                'size'                  => '50mm (2")',
                'connection_type'       => 'Quick-Fit / Socket',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Standar main line pabrik / kompresor 50 HP - 100 HP',
                'price_idr'             => 950000,
            ],
            [
                'item_code'             => 'PIP-ALU-063',
                'category'              => 'pipe',
                'material_type'         => 'Aluminium Airnet / AIRpipe',
                'item_name'             => 'Pipa Aluminium Compressed Air 63mm (2-1/2") x 6m',
                'size'                  => '63mm (2-1/2")',
                'connection_type'       => 'Quick-Fit / Socket',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Main header piping ring line 100 HP - 200 HP',
                'price_idr'             => 1450000,
            ],
            [
                'item_code'             => 'PIP-ALU-080',
                'category'              => 'pipe',
                'material_type'         => 'Aluminium Airnet / AIRpipe',
                'item_name'             => 'Pipa Aluminium Compressed Air 80mm (3") x 6m',
                'size'                  => '80mm (3")',
                'connection_type'       => 'Quick-Fit / Socket',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Heavy industrial main trunk line piping',
                'price_idr'             => 2150000,
            ],
            [
                'item_code'             => 'PIP-GAL-050',
                'category'              => 'pipe',
                'material_type'         => 'Carbon Steel Galvanis Medium',
                'item_name'             => 'Pipa Galvanis Medium SNI 1/2" x 6m (Sch 40)',
                'size'                  => '1/2" (DN15)',
                'connection_type'       => 'Drat / Threaded BSPT',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Pipa besi galvanis anti-karat jalur drop point',
                'price_idr'             => 185000,
            ],
            [
                'item_code'             => 'PIP-GAL-100',
                'category'              => 'pipe',
                'material_type'         => 'Carbon Steel Galvanis Medium',
                'item_name'             => 'Pipa Galvanis Medium SNI 1" x 6m (Sch 40)',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat / Threaded BSPT',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Pipa galvanis distribusi udara mesin produksi',
                'price_idr'             => 310000,
            ],
            [
                'item_code'             => 'PIP-GAL-200',
                'category'              => 'pipe',
                'material_type'         => 'Carbon Steel Galvanis Medium',
                'item_name'             => 'Pipa Galvanis Medium SNI 2" x 6m (Sch 40)',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'Drat / Flange ANSI 150#',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Pipa header utama kompresor & tangki air receiver',
                'price_idr'             => 690000,
            ],
            [
                'item_code'             => 'PIP-SS-100',
                'category'              => 'pipe',
                'material_type'         => 'Stainless Steel SS304',
                'item_name'             => 'Pipa SS304 Seamless / Welded Sch 10 1" x 6m',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'TIG Weld / Socket Weld',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Food grade & pharmaceutical hygienic piping',
                'price_idr'             => 540000,
            ],
            [
                'item_code'             => 'PIP-SS-200',
                'category'              => 'pipe',
                'material_type'         => 'Stainless Steel SS304',
                'item_name'             => 'Pipa SS304 Seamless / Welded Sch 10 2" x 6m',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'TIG Weld / Flange SS304',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'High corrosion resistance main header',
                'price_idr'             => 1120000,
            ],
            [
                'item_code'             => 'PIP-PPR-032',
                'category'              => 'pipe',
                'material_type'         => 'PPR-CT PN20',
                'item_name'             => 'Pipa PPR PN20 High Pressure 32mm (1") x 4m',
                'size'                  => '32mm (1")',
                'connection_type'       => 'Heat Fusion / Sambung Las Panas',
                'unit'                  => 'Batang',
                'length_per_unit'       => 4.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Pipa polimer kompresor bebas karat tahan 20 bar',
                'price_idr'             => 175000,
            ],

            // =========================================================================
            // 2. KATEGORI: FITTING (Sambungan Pipa) - 14 Items
            // =========================================================================
            [
                'item_code'             => 'FIT-ALU-ELB-020',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Equal Elbow 90° Quick-Fit 20mm',
                'size'                  => '20mm (1/2")',
                'connection_type'       => 'Quick-Fit Push-In Lock',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Belokan 90 derajat sistem modular aluminium',
                'price_idr'             => 145000,
            ],
            [
                'item_code'             => 'FIT-ALU-ELB-025',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Equal Elbow 90° Quick-Fit 25mm',
                'size'                  => '25mm (3/4")',
                'connection_type'       => 'Quick-Fit Push-In Lock',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Belokan 90 derajat sistem modular aluminium',
                'price_idr'             => 175000,
            ],
            [
                'item_code'             => 'FIT-ALU-ELB-050',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Equal Elbow 90° Quick-Fit 50mm',
                'size'                  => '50mm (2")',
                'connection_type'       => 'Quick-Fit Clamp Ring',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Belokan 90 derajat header 50mm',
                'price_idr'             => 420000,
            ],
            [
                'item_code'             => 'FIT-ALU-ELB-063',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Equal Elbow 90° Quick-Fit 63mm',
                'size'                  => '63mm (2-1/2")',
                'connection_type'       => 'Quick-Fit Clamp Ring',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Belokan 90 derajat header 63mm',
                'price_idr'             => 650000,
            ],
            [
                'item_code'             => 'FIT-ALU-TEE-025',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Equal Tee Quick-Fit 25mm x 25mm x 25mm',
                'size'                  => '25mm (3/4")',
                'connection_type'       => 'Quick-Fit Push-In Lock',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Percabangan T sama ukuran 25mm',
                'price_idr'             => 230000,
            ],
            [
                'item_code'             => 'FIT-ALU-TEE-050',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Equal Tee Quick-Fit 50mm x 50mm x 50mm',
                'size'                  => '50mm (2")',
                'connection_type'       => 'Quick-Fit Clamp Ring',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Percabangan T main header 50mm',
                'price_idr'             => 560000,
            ],
            [
                'item_code'             => 'FIT-ALU-REDTEE-050-025',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Reducing Tee Quick-Fit 50mm x 25mm x 50mm',
                'size'                  => '50mm x 25mm',
                'connection_type'       => 'Quick-Fit Clamp Ring',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Drop leg cabang dari header 50mm ke jalur 25mm',
                'price_idr'             => 520000,
            ],
            [
                'item_code'             => 'FIT-ALU-SOC-025',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Straight Socket / Coupling Quick-Fit 25mm',
                'size'                  => '25mm (3/4")',
                'connection_type'       => 'Quick-Fit Push-In Lock',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Sambungan lurus pipa aluminium 25mm',
                'price_idr'             => 125000,
            ],
            [
                'item_code'             => 'FIT-ALU-SOC-050',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Straight Socket / Coupling Quick-Fit 50mm',
                'size'                  => '50mm (2")',
                'connection_type'       => 'Quick-Fit Clamp Ring',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Sambungan lurus pipa aluminium 50mm',
                'price_idr'             => 340000,
            ],
            [
                'item_code'             => 'FIT-ALU-RED-050-025',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Reducer Conical Quick-Fit 50mm to 25mm',
                'size'                  => '50mm x 25mm',
                'connection_type'       => 'Quick-Fit',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Pengecilan jalur pipa 2" ke 3/4"',
                'price_idr'             => 290000,
            ],
            [
                'item_code'             => 'FIT-ALU-CAP-050',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'End Cap Quick-Fit 50mm',
                'size'                  => '50mm (2")',
                'connection_type'       => 'Quick-Fit Clamp Ring',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Tutup ujung jalur pipa header 50mm',
                'price_idr'             => 195000,
            ],
            [
                'item_code'             => 'FIT-GAL-ELB-100',
                'category'              => 'fitting',
                'material_type'         => 'Malleable Iron Galvanis',
                'item_name'             => 'Elbow 90° Galvanis Drat BSPT 1" Class 150',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat / Female Threaded',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Fitting drat besi galvanis standar SNI/JIS',
                'price_idr'             => 28000,
            ],
            [
                'item_code'             => 'FIT-GAL-TEE-100',
                'category'              => 'fitting',
                'material_type'         => 'Malleable Iron Galvanis',
                'item_name'             => 'Equal Tee Galvanis Drat BSPT 1" Class 150',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat / Female Threaded',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Percabangan T drat besi galvanis',
                'price_idr'             => 38000,
            ],
            [
                'item_code'             => 'FIT-GAL-NIP-100',
                'category'              => 'fitting',
                'material_type'         => 'Malleable Iron Galvanis',
                'item_name'             => 'Hexagonal Nipple Galvanis Drat Luar 1"',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat Luar / Male Threaded',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Double nepel drat 1 inch',
                'price_idr'             => 22000,
            ],

            // =========================================================================
            // 3. KATEGORI: VALVE (Valve & Instrumentasi) - 12 Items
            // =========================================================================
            [
                'item_code'             => 'VLV-BL-BRS-050',
                'category'              => 'valve',
                'material_type'         => 'Brass Kuningan / WOG',
                'item_name'             => 'Ball Valve Brass Full Port Drat 1/2" PN25 (KITZ / Onda)',
                'size'                  => '1/2" (DN15)',
                'connection_type'       => 'Drat Dalam BSPT',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Kran buka-tutup jalur drop point mesin/alat',
                'price_idr'             => 95000,
            ],
            [
                'item_code'             => 'VLV-BL-BRS-100',
                'category'              => 'valve',
                'material_type'         => 'Brass Kuningan / WOG',
                'item_name'             => 'Ball Valve Brass Full Port Drat 1" PN25 (KITZ / Onda)',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat Dalam BSPT',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Kran isolasi sub-header distribusi udara',
                'price_idr'             => 185000,
            ],
            [
                'item_code'             => 'VLV-BL-BRS-200',
                'category'              => 'valve',
                'material_type'         => 'Brass Kuningan / WOG',
                'item_name'             => 'Ball Valve Brass Full Port Drat 2" PN25 (KITZ)',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'Drat Dalam BSPT',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Main isolation valve header kompresor',
                'price_idr'             => 580000,
            ],
            [
                'item_code'             => 'VLV-BL-SS-100',
                'category'              => 'valve',
                'material_type'         => 'Stainless Steel SS304',
                'item_name'             => 'Ball Valve SS304 3-Piece Full Port Drat 1" 1000 WOG',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat BSPT / NPT',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Heavy duty hygienic ball valve 3-piece',
                'price_idr'             => 420000,
            ],
            [
                'item_code'             => 'VLV-BF-WFR-050',
                'category'              => 'valve',
                'material_type'         => 'Ductile Iron Body + SS304 Disc',
                'item_name'             => 'Butterfly Valve Wafer Type Lever 2" JIS 10K / PN16',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'Wafer Type Diapit Flange',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Katup kupu-kupu sistem tuas untuk header pipa',
                'price_idr'             => 680000,
            ],
            [
                'item_code'             => 'VLV-BF-WFR-080',
                'category'              => 'valve',
                'material_type'         => 'Ductile Iron Body + SS304 Disc',
                'item_name'             => 'Butterfly Valve Wafer Type Lever 3" JIS 10K / PN16',
                'size'                  => '3" (DN80)',
                'connection_type'       => 'Wafer Type Diapit Flange',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Katup kupu-kupu header utama pipa 3 inch',
                'price_idr'             => 890000,
            ],
            [
                'item_code'             => 'VLV-CHK-BRS-100',
                'category'              => 'valve',
                'material_type'         => 'Brass Kuningan',
                'item_name'             => 'Check Valve Spring Loaded Brass Drat 1" PN16',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat Dalam BSPT',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Katup satu arah mencegah aliran balik udara bertekanan',
                'price_idr'             => 210000,
            ],
            [
                'item_code'             => 'VLV-SFT-BRS-050',
                'category'              => 'valve',
                'material_type'         => 'Brass / Bronze',
                'item_name'             => 'Safety Relief Valve Brass 1/2" Preset 10 Bar (Yoshitake / Genebre)',
                'size'                  => '1/2" (DN15)',
                'connection_type'       => 'Drat Luar BSPT',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Pengaman over-pressure pada tangki atau air receiver',
                'price_idr'             => 475000,
            ],
            [
                'item_code'             => 'INST-PG-WIKA-016',
                'category'              => 'valve',
                'material_type'         => 'Stainless Steel + Brass Internal',
                'item_name'             => 'Pressure Gauge 0-16 Bar / 0-230 Psi Dial 2.5" Bottom 1/4" (WIKA / Nagano)',
                'size'                  => 'Dial 2.5", Drat 1/4"',
                'connection_type'       => 'Bottom Connection Drat NPT/BSPT',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Indikator jarum tekanan udara kompresor glycerine filled',
                'price_idr'             => 180000,
            ],
            [
                'item_code'             => 'VLV-STR-BRS-100',
                'category'              => 'valve',
                'material_type'         => 'Brass Kuningan + Mesh SS',
                'item_name'             => 'Y-Strainer Filter Brass Drat 1" PN16 (KITZ / Onda)',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat Dalam BSPT',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Saringan kotoran dan serpihan karat sebelum masuk mesin',
                'price_idr'             => 245000,
            ],
            [
                'item_code'             => 'VLV-DRN-ELC-050',
                'category'              => 'valve',
                'material_type'         => 'Brass Body + Electronic Timer 220V',
                'item_name'             => 'Auto Drain Valve Elektronik Timer Solenoid 1/2" 220VAC (Jorc / SMC)',
                'size'                  => '1/2" (DN15)',
                'connection_type'       => 'Drat Dalam BSPT',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Pembuang air kondensasi otomatis terjadwal',
                'price_idr'             => 490000,
            ],
            [
                'item_code'             => 'INST-FRL-SMC-050',
                'category'              => 'valve',
                'material_type'         => 'Aluminium Die-cast + Polycarbonate Bowl',
                'item_name'             => 'Air Filter Regulator & Lubricator (FRL) Unit 1/2" (SMC / Festo)',
                'size'                  => '1/2" (DN15)',
                'connection_type'       => 'Drat Dalam RC/NPT',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Pengatur tekanan & penyaring partikel debu oli di mesin',
                'price_idr'             => 850000,
            ],

            // =========================================================================
            // 4. KATEGORI: SUPPORT (Support, Hanger & Fastener) - 12 Items
            // =========================================================================
            [
                'item_code'             => 'SUP-STRUT-4141',
                'category'              => 'support',
                'material_type'         => 'Electro Galvanized Steel',
                'item_name'             => 'C-Channel Unistrut Galvanis 41x41x3000mm Tebal 2.0mm',
                'size'                  => '41 x 41 mm',
                'connection_type'       => 'Slotted Channel Baut M10/M12',
                'unit'                  => 'Batang',
                'length_per_unit'       => 3.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Besi kanal C unistrut gantungan pipa plafon / dinding',
                'price_idr'             => 145000,
            ],
            [
                'item_code'             => 'SUP-STRUT-4121',
                'category'              => 'support',
                'material_type'         => 'Electro Galvanized Steel',
                'item_name'             => 'C-Channel Unistrut Galvanis 41x21x3000mm Tebal 1.5mm',
                'size'                  => '41 x 21 mm',
                'connection_type'       => 'Slotted Channel Baut M10',
                'unit'                  => 'Batang',
                'length_per_unit'       => 3.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Besi kanal C unistrut profil rendah untuk bracket dinding',
                'price_idr'             => 110000,
            ],
            [
                'item_code'             => 'SUP-ROD-M10',
                'category'              => 'support',
                'material_type'         => 'Electro Galvanized Steel Grade 4.8',
                'item_name'             => 'Threaded Rod / As Drat M10 x 2000mm Galvanis',
                'size'                  => 'M10 (Diameter 10mm)',
                'connection_type'       => 'Full Thread Drat Metrik',
                'unit'                  => 'Batang',
                'length_per_unit'       => 2.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Besi as drat gantungan pipa ke dak beton atau rangka baja',
                'price_idr'             => 32000,
            ],
            [
                'item_code'             => 'SUP-ROD-M12',
                'category'              => 'support',
                'material_type'         => 'Electro Galvanized Steel Grade 4.8',
                'item_name'             => 'Threaded Rod / As Drat M12 x 2000mm Galvanis',
                'size'                  => 'M12 (Diameter 12mm)',
                'connection_type'       => 'Full Thread Drat Metrik',
                'unit'                  => 'Batang',
                'length_per_unit'       => 2.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'As drat heavy duty untuk pipa ukuran besar 2" ke atas',
                'price_idr'             => 48000,
            ],
            [
                'item_code'             => 'SUP-UBLT-025',
                'category'              => 'support',
                'material_type'         => 'Galvanized Steel + EPDM Rubber Cushion',
                'item_name'             => 'Pipe Clamp U-Bolt w/ Rubber Cushion 1" (25mm)',
                'size'                  => '1" (25mm)',
                'connection_type'       => 'U-Bolt Baut 2 Sisi',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem pipa peredam getaran anti-gores pipa aluminium',
                'price_idr'             => 18500,
            ],
            [
                'item_code'             => 'SUP-UBLT-050',
                'category'              => 'support',
                'material_type'         => 'Galvanized Steel + EPDM Rubber Cushion',
                'item_name'             => 'Pipe Clamp U-Bolt w/ Rubber Cushion 2" (50mm)',
                'size'                  => '2" (50mm)',
                'connection_type'       => 'U-Bolt Baut 2 Sisi',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem U-Bolt header 50mm dengan karet EPDM',
                'price_idr'             => 28000,
            ],
            [
                'item_code'             => 'SUP-HNG-025',
                'category'              => 'support',
                'material_type'         => 'Electro Galvanized Steel',
                'item_name'             => 'Hanger Clamp Split Ring w/ Rod Nut M10 25mm (1")',
                'size'                  => '25mm (1")',
                'connection_type'       => 'Gantungan Drat M10',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem gantung lingkar belah untuk pipa 1 inch',
                'price_idr'             => 14000,
            ],
            [
                'item_code'             => 'SUP-HNG-050',
                'category'              => 'support',
                'material_type'         => 'Electro Galvanized Steel',
                'item_name'             => 'Hanger Clamp Split Ring w/ Rod Nut M10 50mm (2")',
                'size'                  => '50mm (2")',
                'connection_type'       => 'Gantungan Drat M10',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem gantung lingkar belah untuk header pipa 2 inch',
                'price_idr'             => 22000,
            ],
            [
                'item_code'             => 'SUP-BASE-4HOLE',
                'category'              => 'support',
                'material_type'         => 'Hot Dip Galvanized Steel Plate',
                'item_name'             => 'Base Plate Mounting Unistrut 4-Hole 100x100mm',
                'size'                  => '100 x 100 x 6 mm',
                'connection_type'       => 'Baut Dynabolt 4 Titik',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Dudukan plat besi tapak kanal C ke lantai / dinding beton',
                'price_idr'             => 45000,
            ],
            [
                'item_code'             => 'SUP-BEAM-M10',
                'category'              => 'support',
                'material_type'         => 'Ductile Iron Electro Galvanized',
                'item_name'             => 'Beam Clamp Heavy Duty for I-Beam / WF Flange M10',
                'size'                  => 'Klem Sayap WF M10',
                'connection_type'       => 'Jepit Sayap Balok Baja WF / H-Beam',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem gantungan tanpa perlu bor/las balok baja pabrik',
                'price_idr'             => 35000,
            ],
            [
                'item_code'             => 'SUP-DYNA-M10',
                'category'              => 'support',
                'material_type'         => 'Carbon Steel Yellow Galvanized',
                'item_name'             => 'Dynabolt / Anchor Bolt M10 x 65mm',
                'size'                  => 'M10 x 65mm',
                'connection_type'       => 'Expansion Anchor Beton',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Baut tanam beton untuk pasang bracket dan unistrut',
                'price_idr'             => 4500,
            ],
            [
                'item_code'             => 'SUP-LONGNUT-M10',
                'category'              => 'support',
                'material_type'         => 'Carbon Steel Galvanized',
                'item_name'             => 'Long Hex Nut Coupling M10 x 30mm',
                'size'                  => 'M10 x 30mm',
                'connection_type'       => 'Drat Dalam Metrik M10',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Mur panjang penyambung as drat gantung',
                'price_idr'             => 3500,
            ],

            // =========================================================================
            // 5. KATEGORI: CONSUMABLE (Bahan Habis Pakai) - 12 Items
            // =========================================================================
            [
                'item_code'             => 'CON-SEALTAPE-HD',
                'category'              => 'consumable',
                'material_type'         => 'PTFE High Density',
                'item_name'             => 'Seal Tape PTFE Heavy Duty 19mm x 15m (Tombo / Onda)',
                'size'                  => '19mm x 15m',
                'connection_type'       => 'Lilitan Drat Pipa',
                'unit'                  => 'Roll',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Isolasi drat pipa gas dan udara tahan bocor',
                'price_idr'             => 12500,
            ],
            [
                'item_code'             => 'CON-LOCTITE-577',
                'category'              => 'consumable',
                'material_type'         => 'Anaerobic Gel Sealant',
                'item_name'             => 'Liquid Thread Sealant Tube 50ml (Loctite 577 / Visbella)',
                'size'                  => '50 ml',
                'connection_type'       => 'Lem Drat Pipa Logam',
                'unit'                  => 'Tube',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Lem drat cair pengunci dan pencegah kebocoran bertekanan tinggi',
                'price_idr'             => 165000,
            ],
            [
                'item_code'             => 'CON-WELD-RB26',
                'category'              => 'consumable',
                'material_type'         => 'Mild Steel E6013',
                'item_name'             => 'Kawat Las RB-26 3.2mm x 350mm (Kobe Steel, Box 5kg)',
                'size'                  => 'Diameter 3.2mm',
                'connection_type'       => 'SMAW / Las Listrik',
                'unit'                  => 'Box',
                'length_per_unit'       => null,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Elektroda las pipa baja galvanis dan struktur bracket',
                'price_idr'             => 185000,
            ],
            [
                'item_code'             => 'CON-TIG-SS308L',
                'category'              => 'consumable',
                'material_type'         => 'Stainless Steel ER308L',
                'item_name'             => 'Kawat Las Argon TIG Rod SS308L 2.4mm x 1000mm (5kg)',
                'size'                  => 'Diameter 2.4mm',
                'connection_type'       => 'GTAW / TIG Argon Weld',
                'unit'                  => 'Tube',
                'length_per_unit'       => null,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Kawat las pipa stainless steel 304 food grade',
                'price_idr'             => 395000,
            ],
            [
                'item_code'             => 'CON-CUT-4INCH',
                'category'              => 'consumable',
                'material_type'         => 'Aluminium Oxide / Resin Bond',
                'item_name'             => 'Batu Gerinda Potong Cutting Wheel 4" x 1.0mm (Resibon / Bosch)',
                'size'                  => '4" x 1.0 x 16 mm',
                'connection_type'       => 'Mesin Gerinda Tangan 4"',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Mata potong cepat pipa besi, galvanis, dan aluminium',
                'price_idr'             => 9500,
            ],
            [
                'item_code'             => 'CON-GRD-4INCH',
                'category'              => 'consumable',
                'material_type'         => 'Aluminium Oxide / Resin Bond',
                'item_name'             => 'Batu Gerinda Asah Grinding Wheel 4" x 6.0mm (Resibon / Bosch)',
                'size'                  => '4" x 6.0 x 16 mm',
                'connection_type'       => 'Mesin Gerinda Tangan 4"',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Mata poles chamfering ujung pipa dan bekas lasan',
                'price_idr'             => 14500,
            ],
            [
                'item_code'             => 'CON-ARGON-GAS',
                'category'              => 'consumable',
                'material_type'         => 'Gas Argon High Purity 99.99%',
                'item_name'             => 'Gas Argon Murni HP Refill Tabung 6m3 (40 Liter)',
                'size'                  => '6 m3 (150 Bar)',
                'connection_type'       => 'Regulator Gas Argon',
                'unit'                  => 'Tabung',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Gas pelindung proses pengelasan TIG pipa stainless steel',
                'price_idr'             => 285000,
            ],
            [
                'item_code'             => 'CON-GSK-050',
                'category'              => 'consumable',
                'material_type'         => 'Non-Asbestos Gasket Sheet (Valqua / Klinger)',
                'item_name'             => 'Gasket Flange Non-Asbestos ANSI 150# RF 2" Tebal 3mm',
                'size'                  => '2" (DN50) ANSI 150#',
                'connection_type'       => 'Flange Connection Joint',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Paking pencegah kebocoran sambungan flange 2 inch',
                'price_idr'             => 35000,
            ],
            [
                'item_code'             => 'CON-BLT-M16',
                'category'              => 'consumable',
                'material_type'         => 'High Tensile Steel Grade 8.8 Galvanized',
                'item_name'             => 'Baut & Mur Hex Bolt M16 x 65mm Full Drat Grade 8.8 + 2 Ring',
                'size'                  => 'M16 x 65 mm',
                'connection_type'       => 'Baut Flange 2" - 3"',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Set baut mur galvanis standar pengencang flange pipa',
                'price_idr'             => 16500,
            ],
            [
                'item_code'             => 'CON-BLT-M12',
                'category'              => 'consumable',
                'material_type'         => 'High Tensile Steel Grade 8.8 Galvanized',
                'item_name'             => 'Baut & Mur Hex Bolt M12 x 45mm Full Drat Grade 8.8 + 2 Ring',
                'size'                  => 'M12 x 45 mm',
                'connection_type'       => 'Baut Flange / Bracket',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Set baut mur pengencang bracket unistrut',
                'price_idr'             => 9500,
            ],
            [
                'item_code'             => 'CON-PAINT-ZINC',
                'category'              => 'consumable',
                'material_type'         => 'Alkyd Resin + Zinc Phosphate',
                'item_name'             => 'Cat Anti-Karat Zinc Chromate Primer (Kansai / Nippon, Galon 5kg)',
                'size'                  => 'Galon 5 kg',
                'connection_type'       => 'Kuas / Roll / Spray',
                'unit'                  => 'Galon',
                'length_per_unit'       => null,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Cat pelindung anti-karat sambungan las dan bracket besi',
                'price_idr'             => 260000,
            ],
            [
                'item_code'             => 'CON-FOAM-PU',
                'category'              => 'consumable',
                'material_type'         => 'Polyurethane Foam Spray',
                'item_name'             => 'PU Foam Sealant Expansion Spray Can 750ml (Penosil / Sika)',
                'size'                  => 'Can 750 ml',
                'connection_type'       => 'Aerosol Nozzle Spray',
                'unit'                  => 'Can',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Busa perapat celah lubang tembus dinding / partisi pipa',
                'price_idr'             => 78000,
            ],

            // =========================================================================
            // 6. SUPPLEMENTARY ITEMS (Anti-Vibrasi, Flange, Quick Coupler, Besi Siku, PU Hose, Leak Spray)
            // =========================================================================
            // PIPE & FLEXIBLE JOINTS
            [
                'item_code'             => 'PIP-FLX-SS-100',
                'category'              => 'pipe',
                'material_type'         => 'Stainless Steel SS304 Braided',
                'item_name'             => 'Flexible Metal Hose SS304 Braided Drat Luar 1" x 500mm',
                'size'                  => '1" (DN25) x 500mm',
                'connection_type'       => 'Drat Luar Male BSPT 2 Sisi',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Selang anyaman SS peredam getaran output kompresor/dryer',
                'price_idr'             => 385000,
            ],
            [
                'item_code'             => 'PIP-FLX-SS-150',
                'category'              => 'pipe',
                'material_type'         => 'Stainless Steel SS304 Braided',
                'item_name'             => 'Flexible Metal Hose SS304 Braided Flange ANSI 150# 1-1/2" x 500mm',
                'size'                  => '1-1/2" (DN40) x 500mm',
                'connection_type'       => 'Flange Flotting 2 Sisi ANSI 150#',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Peredam vibrasi mesin kompresor kapasitas sedang 30-50 HP',
                'price_idr'             => 650000,
            ],
            [
                'item_code'             => 'PIP-FLX-SS-200',
                'category'              => 'pipe',
                'material_type'         => 'Stainless Steel SS304 Braided',
                'item_name'             => 'Flexible Metal Hose SS304 Braided Flange ANSI 150# 2" x 500mm',
                'size'                  => '2" (DN50) x 500mm',
                'connection_type'       => 'Flange Flotting 2 Sisi ANSI 150#',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Peredam getaran pipa discharge kompresor 50-100 HP',
                'price_idr'             => 890000,
            ],
            [
                'item_code'             => 'PIP-RUB-FLX-200',
                'category'              => 'pipe',
                'material_type'         => 'EPDM Rubber + Carbon Steel Flange',
                'item_name'             => 'Rubber Expansion Joint Bellow Single Sphere Flange JIS 10K 2"',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'Flange JIS 10K / ANSI 150#',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Karet fleksibel bellow sambungan tangki air receiver',
                'price_idr'             => 450000,
            ],
            [
                'item_code'             => 'PIP-CS-SCH40-100',
                'category'              => 'pipe',
                'material_type'         => 'Carbon Steel Seamless ASTM A106 Grade B',
                'item_name'             => 'Pipa Carbon Steel Seamless Sch 40 1" x 6m (Hitam)',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Las / Bevel End',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Pipa baja hitam seamless tahan tekanan tinggi dan temperatur',
                'price_idr'             => 420000,
            ],
            [
                'item_code'             => 'PIP-CS-SCH40-200',
                'category'              => 'pipe',
                'material_type'         => 'Carbon Steel Seamless ASTM A106 Grade B',
                'item_name'             => 'Pipa Carbon Steel Seamless Sch 40 2" x 6m (Hitam)',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'Las / Bevel End',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Pipa baja hitam header utama instalasi kompresor',
                'price_idr'             => 850000,
            ],

            // FITTINGS (FLANGE, UNION, SADDLE & BARB)
            [
                'item_code'             => 'FIT-FLG-CS-100',
                'category'              => 'fitting',
                'material_type'         => 'Forged Carbon Steel A105',
                'item_name'             => 'Flange Slip-On Carbon Steel ANSI 150# RF 1"',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Las Sambung Pipa + 4 Lubang Baut',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Flange baja sambungan inlet/outlet filter atau tangki',
                'price_idr'             => 85000,
            ],
            [
                'item_code'             => 'FIT-FLG-CS-200',
                'category'              => 'fitting',
                'material_type'         => 'Forged Carbon Steel A105',
                'item_name'             => 'Flange Slip-On Carbon Steel ANSI 150# RF 2"',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'Las Sambung Pipa + 4 Lubang Baut',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Flange baja sambungan main header 2 inch',
                'price_idr'             => 145000,
            ],
            [
                'item_code'             => 'FIT-FLG-SS-100',
                'category'              => 'fitting',
                'material_type'         => 'Stainless Steel SS304 Forged',
                'item_name'             => 'Flange Slip-On SS304 ANSI 150# RF 1"',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Las TIG Stainless + 4 Lubang Baut',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Flange stainless steel anti-korosi',
                'price_idr'             => 175000,
            ],
            [
                'item_code'             => 'FIT-FLG-SS-200',
                'category'              => 'fitting',
                'material_type'         => 'Stainless Steel SS304 Forged',
                'item_name'             => 'Flange Slip-On SS304 ANSI 150# RF 2"',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'Las TIG Stainless + 4 Lubang Baut',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Flange stainless steel 2 inch',
                'price_idr'             => 320000,
            ],
            [
                'item_code'             => 'FIT-ALU-SDL-050-025',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Quick Drop Saddle Clamp Aluminium 50mm x 25mm (Gooseneck)',
                'size'                  => '50mm x 25mm',
                'connection_type'       => 'Clamp-On Saddle Body',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem sadel cabang drop point anti-kondensasi tanpa potong pipa',
                'price_idr'             => 275000,
            ],
            [
                'item_code'             => 'FIT-ALU-SDL-063-025',
                'category'              => 'fitting',
                'material_type'         => 'Aluminium / Engineered Polymer',
                'item_name'             => 'Quick Drop Saddle Clamp Aluminium 63mm x 25mm (Gooseneck)',
                'size'                  => '63mm x 25mm',
                'connection_type'       => 'Clamp-On Saddle Body',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem sadel cabang drop point untuk header 63mm',
                'price_idr'             => 340000,
            ],
            [
                'item_code'             => 'FIT-UNI-GAL-100',
                'category'              => 'fitting',
                'material_type'         => 'Malleable Iron Galvanis',
                'item_name'             => 'Union Drat Besi Galvanis Female 1" Class 150',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat Dalam BSPT 3-Piece',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Sambungan watermur galvanis untuk kemudahan bongkar pasang',
                'price_idr'             => 58000,
            ],
            [
                'item_code'             => 'FIT-UNI-SS-100',
                'category'              => 'fitting',
                'material_type'         => 'Stainless Steel SS304',
                'item_name'             => 'Union Drat Stainless Steel SS304 Female 1"',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat Dalam BSPT / NPT Conical Seat',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Watermur stainless steel 304 food grade',
                'price_idr'             => 145000,
            ],
            [
                'item_code'             => 'FIT-NIP-BARB-050',
                'category'              => 'fitting',
                'material_type'         => 'Brass Kuningan Padat',
                'item_name'             => 'Hose Barb Nipple Brass Drat Luar 1/2" x Ekor Selang 1/2" (12mm)',
                'size'                  => '1/2" x 1/2"',
                'connection_type'       => 'Drat Luar Male BSPT x Selang Klem',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Nepel konektor dari kran pipa ke selang karet/spiral',
                'price_idr'             => 28000,
            ],

            // VALVES & QUICK COUPLERS & LINE FILTERS
            [
                'item_code'             => 'VLV-CPL-NITTO-20',
                'category'              => 'valve',
                'material_type'         => 'Hardened Steel Chrome Plated',
                'item_name'             => 'Quick Coupler Air One-Touch Set (Socket 20SM + Plug 20PM 1/4")',
                'size'                  => '1/4" (Type 20)',
                'connection_type'       => 'Drat Luar Male 1/4" BSPT Quick Click',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Kopler lepas pasang cepat selang angin mesin/spray gun',
                'price_idr'             => 45000,
            ],
            [
                'item_code'             => 'VLV-CPL-NITTO-30',
                'category'              => 'valve',
                'material_type'         => 'Hardened Steel Chrome Plated',
                'item_name'             => 'Quick Coupler Air One-Touch Set (Socket 30SM + Plug 30PM 3/8")',
                'size'                  => '3/8" (Type 30)',
                'connection_type'       => 'Drat Luar Male 3/8" BSPT Quick Click',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Kopler selang angin kapasitas medium',
                'price_idr'             => 55000,
            ],
            [
                'item_code'             => 'VLV-CPL-NITTO-40',
                'category'              => 'valve',
                'material_type'         => 'Hardened Steel Chrome Plated',
                'item_name'             => 'Quick Coupler Air One-Touch Set (Socket 40SM + Plug 40PM 1/2")',
                'size'                  => '1/2" (Type 40)',
                'connection_type'       => 'Drat Luar Male 1/2" BSPT Quick Click',
                'unit'                  => 'Set',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Kopler heavy duty aliran udara besar impact wrench',
                'price_idr'             => 65000,
            ],
            [
                'item_code'             => 'INST-FILT-LINE-100',
                'category'              => 'valve',
                'material_type'         => 'Die-Cast Aluminium Housing + Micro-Fiber Filter',
                'item_name'             => 'Main Line Compressed Air Filter Coalescing 0.01 Micron 1" (Hankison/SMC)',
                'size'                  => '1" (DN25)',
                'connection_type'       => 'Drat Dalam BSPT',
                'unit'                  => 'Unit',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Filter penyaring uap oli dan air presisi tinggi',
                'price_idr'             => 1450000,
            ],
            [
                'item_code'             => 'INST-FILT-LINE-200',
                'category'              => 'valve',
                'material_type'         => 'Die-Cast Aluminium Housing + Micro-Fiber Filter',
                'item_name'             => 'Main Line Compressed Air Filter Coalescing 0.01 Micron 2" (Hankison/SMC)',
                'size'                  => '2" (DN50)',
                'connection_type'       => 'Drat / Flange 2"',
                'unit'                  => 'Unit',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Filter jalur utama udara bertekanan kompresor kapasitas besar',
                'price_idr'             => 2850000,
            ],

            // SUPPORT & STRUCTURAL STEEL
            [
                'item_code'             => 'SUP-ANG-4040',
                'category'              => 'support',
                'material_type'         => 'Mild Steel SNI Hot Rolled',
                'item_name'             => 'Besi Siku Equal Angle Bar L 40x40x4mm x 6m',
                'size'                  => '40 x 40 x 4 mm',
                'connection_type'       => 'Las / Baut Rangka Support',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Besi siku pembuatan tiang bracket gantung dan penyangga pipa',
                'price_idr'             => 185000,
            ],
            [
                'item_code'             => 'SUP-ANG-5050',
                'category'              => 'support',
                'material_type'         => 'Mild Steel SNI Hot Rolled',
                'item_name'             => 'Besi Siku Equal Angle Bar L 50x50x5mm x 6m',
                'size'                  => '50 x 50 x 5 mm',
                'connection_type'       => 'Las / Baut Rangka Support',
                'unit'                  => 'Batang',
                'length_per_unit'       => 6.00,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Besi siku tiang tumpuan pipa heavy duty lintas gedung',
                'price_idr'             => 295000,
            ],
            [
                'item_code'             => 'SUP-BRK-WALL-300',
                'category'              => 'support',
                'material_type'         => 'Electro Galvanized Steel',
                'item_name'             => 'Bracket Cantilever Arm Wall Mount Unistrut 300mm Heavy Duty',
                'size'                  => 'Panjang 300mm',
                'connection_type'       => 'Baut Dynabolt 2 Titik Dinding',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Siku gantung jadi untuk menopang pipa di sepanjang dinding',
                'price_idr'             => 65000,
            ],
            [
                'item_code'             => 'SUP-BRK-WALL-500',
                'category'              => 'support',
                'material_type'         => 'Electro Galvanized Steel',
                'item_name'             => 'Bracket Cantilever Arm Wall Mount Unistrut 500mm Heavy Duty',
                'size'                  => 'Panjang 500mm',
                'connection_type'       => 'Baut Dynabolt 2 Titik Dinding',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Siku gantung panjang untuk jalur ganda pipa di dinding',
                'price_idr'             => 95000,
            ],
            [
                'item_code'             => 'SUP-CLMP-OMG-025',
                'category'              => 'support',
                'material_type'         => 'Galvanized Steel Strip',
                'item_name'             => 'Omega / Saddle Clamp Kancing Galvanis 1" (25mm)',
                'size'                  => '1" (25mm)',
                'connection_type'       => 'Sekrup / Baut 2 Sisi',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem tempel langsung ke dinding kolom beton atau besi siku',
                'price_idr'             => 6500,
            ],
            [
                'item_code'             => 'SUP-CLMP-OMG-050',
                'category'              => 'support',
                'material_type'         => 'Galvanized Steel Strip',
                'item_name'             => 'Omega / Saddle Clamp Kancing Galvanis 2" (50mm)',
                'size'                  => '2" (50mm)',
                'connection_type'       => 'Sekrup / Baut 2 Sisi',
                'unit'                  => 'Pcs',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Klem tempel pipa 2 inch ke dinding/struktur',
                'price_idr'             => 11000,
            ],

            // CONSUMABLE, TESTING & SAFETY
            [
                'item_code'             => 'CON-HOSE-PU-8X5',
                'category'              => 'consumable',
                'material_type'         => 'Polyurethane (PU) Flexible Tubing',
                'item_name'             => 'Selang Angin PU (Polyurethane) 8mm x 5mm Biru / Transparan (Roll 100m)',
                'size'                  => 'OD 8mm x ID 5mm x 100m',
                'connection_type'       => 'One-Touch Quick Fitting',
                'unit'                  => 'Roll',
                'length_per_unit'       => null,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Selang angin lentur penghubung kran ke mesin produksi/silinder pneumatik',
                'price_idr'             => 380000,
            ],
            [
                'item_code'             => 'CON-HOSE-PU-10X65',
                'category'              => 'consumable',
                'material_type'         => 'Polyurethane (PU) Flexible Tubing',
                'item_name'             => 'Selang Angin PU (Polyurethane) 10mm x 6.5mm Biru / Transparan (Roll 100m)',
                'size'                  => 'OD 10mm x ID 6.5mm x 100m',
                'connection_type'       => 'One-Touch Quick Fitting',
                'unit'                  => 'Roll',
                'length_per_unit'       => null,
                'default_waste_percent' => 5.00,
                'notes'                 => 'Selang angin lentur kapasitas aliran lebih besar',
                'price_idr'             => 560000,
            ],
            [
                'item_code'             => 'CON-LEAK-SPRAY',
                'category'              => 'consumable',
                'material_type'         => 'Surfactant Gas Leak Detector Foam',
                'item_name'             => 'Air Leak Detector Foam Spray Can 400ml',
                'size'                  => 'Can 400 ml',
                'connection_type'       => 'Aerosol Spray',
                'unit'                  => 'Can',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Busa pendeteksi kebocoran sambungan saat uji tekan hydrotest/komisioning',
                'price_idr'             => 68000,
            ],
            [
                'item_code'             => 'CON-STK-LABEL-AIR',
                'category'              => 'consumable',
                'material_type'         => 'Vinyl Self-Adhesive UV Resistant',
                'item_name'             => 'Stiker Label Identifikasi Pipa "COMPRESSED AIR" + Panah Aliran (Pack 20 Pcs)',
                'size'                  => '20 x 5 cm',
                'connection_type'       => 'Sticker Tempel Pipa',
                'unit'                  => 'Pack',
                'length_per_unit'       => null,
                'default_waste_percent' => 0.00,
                'notes'                 => 'Marka wajib standar K3 dan audit ISO industri',
                'price_idr'             => 45000,
            ],
        ];

        DB::beginTransaction();
        try {
            $insertedCount = 0;
            foreach ($items as $item) {
                $priceIdr = $item['price_idr'] ?? null;
                unset($item['price_idr']);

                $material = PipingMaterial::updateOrCreate(
                    ['item_code' => $item['item_code']],
                    $item
                );

                if ($defaultSupId && $priceIdr) {
                    PipingMaterialVendorPrice::updateOrCreate(
                        [
                            'id_piping_material' => $material->id,
                            'id_supplier'        => $defaultSupId,
                        ],
                        [
                            'price_idr'  => $priceIdr,
                            'date'       => now()->toDateString(),
                            'notes'      => 'Harga estimasi katalog standar vendor',
                            'is_primary' => true,
                        ]
                    );
                }

                $insertedCount++;
            }

            DB::commit();
            $this->command->info("Berhasil menambahkan {$insertedCount} master material piping lengkap dengan HPP vendor!");
        } catch (\Exception $e) {
            DB::rollBack();
            $this->command->error("Gagal menambahkan material piping: " . $e->getMessage());
        }
    }
}
