<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = [
            [
                'nip' => '1',
                'name' => 'Yusuf Herdiana',
                'email' => 'sales@reftech.id',
                'password' => Hash::make('sales123'),
                'phone' => '+6282320000852',
                "image" => "asset/profile/VUa9uNxd.jpg",
                'sign' => NULL,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'YH',
                'active' => '1',
                'role' => 'Sales',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [

                'nip' => '1',
                'name' => 'Regita Dwi Melinda',
                'email' => 'regita@reftech.id',
                'password' => Hash::make('sales123'),
                "image" => "asset/profile/zAIMgCa5.jpg",
                "phone" => "+6282210008917",
                'sign' => NULL,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'RM',
                'active' => '1',
                'role' => 'Sales',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Rifan Fahli',
                'email' => 'rifan@reftech.id',
                'password' => Hash::make('sales123'),
                "image" => "asset/profile/OtKzCnqu.jpg",
                "phone" => "+6281210008462",
                'sign' => NULL,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'RF',
                'active' => '1',
                'role' => 'Sales',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Yolan Yolanda',
                'email' => 'support@reftech.id',
                'password' => Hash::make('sales123'),
                "image" => "asset/profile/KiskxxTi.jpg",
                'phone' => '-',
                'sign' => NULL,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'CRM',
                'active' => '1',
                'role' => 'Sales',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Angel Irene',
                'email' => 'irene@reftech.id',
                'password' => Hash::make('admin123'),
                "image" => "asset/profile/qJ0rN7Br.jpg",
                'phone' => '-',
                'sign' => NULL,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'ADM-I',
                'active' => '1',
                'roles' => 'Admin',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Arief Rachman',
                'email' => 'arief@reftech.id',
                'password' => Hash::make('admin123'),
                "image" => "asset/profile/1Ybgg5U0.jpg",
                'phone' => '-',
                'sign' => NULL,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'ADM-A',
                'active' => '1',
                'roles' => 'Admin',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Admin Reftech',
                'phone' => '-',
                'email' => 'admin@reftech.id',
                'password' => Hash::make('admin123'),
                "image" => "asset/profile/profile.jpg",
                'sign' => NULL,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'ADM-R',
                'active' => '1',
                'roles' => 'Admin',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Tedi Mulyadi',
                'phone' => '-',
                'email' => 'tedi@reftech.id',
                'password' => Hash::make('teknisi123'),
                "image" => "asset/profile/iUJIVVv4.png",
                "sign" => "asset/reports/sign/technician/tedy.png",
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'TMU',
                'active' => '1',
                'roles' => 'Technician',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Candra Wahyudi',
                "phone" => "+62813-5000-3998",
                'email' => 'candra@reftech.id',
                'password' => Hash::make('teknisi123'),
                "image" => "asset/profile/Gj9WRbUr.jpg",
                "sign" => "asset/reports/sign/technician/candra.png",
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'CWA',
                'active' => '1',
                'roles' => 'Technician',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Trimo Susandanu',
                "phone" => "+62-82216207024",
                'email' => 'danu@reftech.id',
                'password' => Hash::make('teknisi123'),
                "image" => "asset/profile/XvbnwQAf.jpg",
                "sign" => "asset/reports/sign/technician/trimo.png",
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'TSU',
                'active' => '1',
                'roles' => 'Technician',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                "name" => "Lukiyanto",
                "phone" => "+6282286830300",
                "email" => "lukiy@reftech.id",
                'password' => Hash::make('logistik123'),
                "image" => "asset/profile/profile.jpg",
                "sign" => null,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'LYZ',
                'active' => '1',
                'roles' => 'Admin',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                'name' => 'Faris Abu Hafidz',
                'phone' => '-',
                'email' => 'faris@reftech.id',
                'password' => Hash::make('teknisi123'),
                "image" => "asset/profile/K4qvWMQJ.jpg",
                "sign" => "asset/reports/sign/technician/faris.png",
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'FAH',
                'active' => '1',
                'roles' => 'Technician',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                "name" => "M Supriyadi Tutun",
                "phone" => "+6282121921172",
                "email" => "supriadi@reftech.id",
                'password' => Hash::make('teknisi123'),
                "image" => "asset/profile/U0nJz64D.png",
                "sign" => "asset/reports/sign/technician/tutun.png",
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'MST',
                'active' => '1',
                'roles' => 'Technician',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                "name" => "Derry Barmanto",
                "phone" => "+6282180006012",
                "email" => "derry@reftech.id",
                'password' => Hash::make('sales123'),
                "image" => "asset/profile/N2OsbMwE.jpg",
                "sign" => null,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'DB',
                'active' => '0',
                'roles' => 'Sales',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                "name" => "Eri Kurnia",
                "phone" => "+62823-2020-9811",
                "email" => "eri@reftech.id",
                'password' => Hash::make('sales123'),
                "image" => "asset/profile/HvVZS3Xu.jpg",
                "sign" => null,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'EKU',
                'active' => '1',
                'roles' => 'Sales',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                "name" => "Ari Sudewo",
                "phone" => "+62895329683129",
                "email" => "wowo@reftech.id",
                'password' => Hash::make('sales123'),
                "image" => "asset/profile/Ax0J8lRK.png",
                "sign" => null,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'ARI',
                'active' => '1',
                'roles' => 'Sales',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                "name" => "Fajar Usman",
                "phone" => "+62+6281384047163",
                "email" => "fajar@reftech.id",
                'password' => Hash::make('logistik123'),
                "image" => "asset/profile/iwzZugVm.jpg",
                "sign" => null,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'FTW',
                'active' => '1',
                'roles' => 'Logistic',
                'date_in' => \Carbon\Carbon::today(),
            ],
            [
                'nip' => '1',
                "name" => "Rian Aprian",
                "phone" => "+6281320583277",
                "email" => "rian@reftech.id",
                'password' => Hash::make('gudang123'),
                "image" => "asset/profile/profile.jpg",
                "sign" => null,
                'birthday' => \Carbon\Carbon::today(),
                'address' => '-',
                'code' => 'LYZ',
                'active' => '1',
                'roles' => 'Logistic',
                'date_in' => \Carbon\Carbon::today(),
            ],
        ];
        User::insert($user);
    }
}
