@if (($adminView ?? 'sales') === 'developer')
    @include('pages.developer.dashboard_content')
@elseif (($adminView ?? 'sales') === 'salesmanager')
    @include('pages.salesmanager.dashboard._content')
@elseif (($adminView ?? 'sales') === 'accounting')
    @include('pages.accounting.dashboard._content')
@elseif (($adminView ?? 'sales') === 'finance')
    @include('pages.finance.dashboard._content')
@elseif (($adminView ?? 'sales') === 'logistic')
    @include('pages.logistic.dashboard._content')
@elseif (($adminView ?? 'sales') === 'workshop')
    @include('pages.workshop.dashboard._content')
@elseif (($adminView ?? 'sales') === 'hr')
    @include('pages.hr.dashboard._content')
@elseif (($adminView ?? 'sales') === 'projectmanager')
    @include('pages.projectmanager.dashboard._content')
@elseif (($adminView ?? 'sales') === 'clientvendor')
    @include('pages.clientvendor.dashboard._content')
@else
    @include('pages.sales.dashboard_admin_sales')
@endif

